version: '3.8'

services:
  app:
    container_name: nodejs-typescript-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: npm start
